######################### GUGUBot设置 #################################

GUGUBot:
  command_prefix: "#"   # 命令前缀
  group_admin: false   # 群指令 :: 只能被咱们的管理员执行

  show_message_in_console: true   # 展示上报消息

########################### 连接设置 ##################################

connector:
  QQ:   # QQ连接器
    source_name: "QQ" # QQ 显示名称
    enable: true # 是否启用
    connection:
      host: 127.0.0.1 # 主机地址
      port: 8777 # 端口
      post_path: "" # 路径
      use_ssl: false # 是否使用SSL
      verify: true # 是否验证证书
      ca_certs: "" # 证书路径
      sslopt: {} # SSL选项
      reconnect: 5 # 重连时间
      max_wait_time: 5 # 最大等待时间
      token: "" # QQ 令牌
    permissions:
      admin_ids:       # 管理员QQ号
      - 1377820366
      - 

      admin_group_ids:        # 管理群群号 :: (可选)群内所有成员拥有管理权限
      - 
      - 

      group_ids:       # qq群号 :: 要监听，转发的qq群号
      - 12345615646416

      friend_is_admin: false       # 好友即是管理 :: 开放管理权限给机器人好友
      custom_group_name:       # 自定义游戏内显示群名 :: （可选）不设置默认转发[群名称]
        726741344: 定制的显示群名         # 如无需自定义，无视这行

    others:
      forward_other_bot: false       # 转发官方机器人回复

  minecraft:   # Minecraft连接器
    source_name: "Minecraft" # 服务器显示名称 :: 如果是主服务器，会显示这个名称
    enable: true # 是否启用

    mc_achievement: true     # 转发 MC 成就
    mc_death: true     # 转发 MC 死亡消息
    player_notice: false     # 玩家上下线通知
    server_start_notice: true     # 服务器启动通知
    server_stop_notice: true     # 服务器停止通知

    ignore_mc_command_patterns: 
    - "!!.*" # 忽略MCDR指令
    - ".*?\\[Command: /.*\\]" # carpet 指令记录
    - ".*?xaero-waypoint:.*" # 忽略 Xaero Waypoint 的共享

  minecraft_bridge:   # Minecraft桥接器
    source_name: "Bridge" # 桥接服务器显示名称 :: 如果不是主服务器，会显示这个名称
    enable: true # 是否启用

    is_main_server: true     # 是否为主服务器 :: 发送消息到其他服务器

    connection: # 桥接服务器连接设置
      host: 127.0.0.1 # 主机地址
      port: 8787 # 端口
      use_ssl: false # 是否使用SSL
      verify: true # 是否验证证书
      ca_certs: "" # 证书路径
      sslopt: {} # SSL选项
      reconnect: 5 # 重连时间
      max_wait_time: 5 # 最大等待时间
      token: "" # 令牌

########################### 风格设置 ##################################

style:
  current_style: 正常   # 机器人回复风格 :: （可选） #风格 查看风格帮助
  style_cooldown: 0   # 风格切换冷却

########################### 系统设置 ##################################

system:
  ban_words:   # 违禁词撤回
    enable: false

  bound:   # 绑定系统
    enable: false

    bound_notice: true     # 绑定提示 :: 是否进行绑定提示
    max_bedrock_bound: 1
    max_java_bound: 1

    whitelist_add_with_bound: false   # 绑定ID自动绑定服务器白名单
    whitelist_remove_with_leave: true   # 退群时移除白名单

  echo:   # 转发系统
    enable: true

  execute_command: # 执行服务器指令
    enable: false

  key_words:   # 关键词回复
    enable: true
    max_add_time: 30 # 最大添加时间(秒) :: 超过这个时间后，关键词添加会过期

  list:   # 在线玩家查询
    enable: false

  name:   # 机器人昵称
    enable: false

  start_command:   # 开服指令
    enable: false

  startup_command:   # 启动指令
    enable: false

  whitelist:   # 白名单
    enable: false
